name: 'Get code & Dependencies'
description: 'get dependinces and code'
inputs:
  caching:
    description: "wheter to cache depednceis or not."
    required: false
    deafult : 'true'
runas: 
  using: 'composite'
  steps: 
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash