name: 'Get code & Dependencies'
description: 'Get dependencies and code'
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: 'false'
  parameter:
    description: "Cache key for dependencies"
    required: false
outputs:
  used-cache: 'Cache was used.'
  value: ${{ steps.get-result.outputs.cache }}  # Correct output reference

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      uses: actions/cache@v3  # Example caching action

    - name: Run
      run: echo "Running command with parameter: ${{ inputs.parameter }}"
      shell: bash
      id: get-result

    - name: Get result
      run: echo "cache=${{ inputs.parameter }}" >> $GITHUB_OUTPUT  # Corrected output setting
      shell: bash
      id: get-result
