name: 'Get code & Dependencies'
description: 'Get dependencies and code'
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: 'true'
  cache-key:
    description: "Cache key for dependencies"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ inputs.cache-key }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
