name: 'Get code & Dependencies'
description: 'Get dependencies and code'
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: 'false'
  parameter:
    description: "Cache key for dependencies"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
    - name: "run"
      run: ${{inputs.parameter}}