name: 'Deploy to  AWS S3'
description: 'Deploy a static page website via AWS S3.'
inputs: 
  bucket:
    description: 'The s3 bucket name '
    required: true
  bucket-region:
    description: 'bucket region'
    required: false
    default: 'eu-north-1'
  dist-folder:
    description: 'the folder containing the deployable files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'