name: First workflow
# on key you defined the event that should trigger the workflow to run
# workflowdispatch means we can manualy trigger this workflow 
on: workflow_dispatch
# it's jobs it nob 
jobs: 
  patrick-job:
    # it's the runner
    runs-on: ubuntu-latest
    steps:
      - name : Printing Name
        run: echo "Hello World"
      - name : Printing Goodbye
        run : echo "Goodbye! - Done"
