name: Second_Task
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Building Code
        run: npm run build
      - name: Deploying Code
        run : echo "Deploying....."
